bugfix to change PSAD_VERSION var to GPGDIR_VERSION
git-svn-id: file:///home/mbr/svn/gpgdir_repos/gpgdir/trunk@183 958e171a-1414-0410-8e2f-9d295d3c0db0

diff --git a/packaging/gpgdir.SlackBuild b/packaging/gpgdir.SlackBuild
--- a/packaging/gpgdir.SlackBuild
+++ b/packaging/gpgdir.SlackBuild
@@ -6,7 +6,7 @@ declare -r  RPM_BUILDER="http://www.cipherdyne.org/scripts/cd_rpmbuilder.tar.gz"
 declare -r  RPM_ROOT_DIR="/usr/src/rpm"
 declare -r  ARCH="i386"
 declare -ri BUILD=1
-PSAD_VERSION=`wget --no-verbose --output-document=- http://www.cipherdyne.org/gpgdir/gpgdir-latest` || {
+GPGDIR_VERSION=`wget --no-verbose --output-document=- http://www.cipherdyne.org/gpgdir/gpgdir-latest` || {
   echo "error!" 1>&2
   exit 1
 }
@@ -16,12 +16,12 @@ wget --no-verbose --output-document=- "${RPM_BUILDER}" | tar xz --to-stdout | pe
   echo "error!" 1>&2
   exit 1
 }
-[ ! -f "${RPM_ROOT_DIR}/RPMS/${ARCH}/gpgdir-${PSAD_VERSION}-${BUILD}.${ARCH}.rpm" ] && {
-  echo "error: file \`gpgdir-${PSAD_VERSION}-${BUILD}.${ARCH}.rpm' doesn't exist!" 1>&2
+[ ! -f "${RPM_ROOT_DIR}/RPMS/${ARCH}/gpgdir-${GPGDIR_VERSION}-${BUILD}.${ARCH}.rpm" ] && {
+  echo "error: file \`gpgdir-${GPGDIR_VERSION}-${BUILD}.${ARCH}.rpm' doesn't exist!" 1>&2
   exit 1
 }
 pushd "${RPM_ROOT_DIR}/RPMS/${ARCH}"			|| exit 1
-rpm2tgz "gpgdir-${PSAD_VERSION}-${BUILD}.${ARCH}.rpm"	|| exit 1
-mv -v "gpgdir-${PSAD_VERSION}-${BUILD}.${ARCH}.tgz" "gpgdir-${PSAD_VERSION}-${ARCH}-${BUILD}.tgz" || exit 1
-ls -l "${RPM_ROOT_DIR}/RPMS/${ARCH}/gpgdir-${PSAD_VERSION}-${ARCH}-${BUILD}.tgz"
+rpm2tgz "gpgdir-${GPGDIR_VERSION}-${BUILD}.${ARCH}.rpm"	|| exit 1
+mv -v "gpgdir-${GPGDIR_VERSION}-${BUILD}.${ARCH}.tgz" "gpgdir-${GPGDIR_VERSION}-${ARCH}-${BUILD}.tgz" || exit 1
+ls -l "${RPM_ROOT_DIR}/RPMS/${ARCH}/gpgdir-${GPGDIR_VERSION}-${ARCH}-${BUILD}.tgz"
 exit ${?}
